image: node:alpine

stages:
  - build

job:
  tags:
    - iprofiler

react_build:
  stage: build
  before_script:
    - echo "Installing NPM Dependencies and building React app"
  script:
    - npm install
    - npm run build
  after_script:
    - echo "Installation and build successful"
  cache:
    key: install-cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
