stages:
  # - build
  - py_build

# react_build:
#   stage: build
#   tags:
#     - iprofiler
#   before_script:
#     - echo "Installing NPM Dependencies and building React app"
#     - cd react-app
#     - echo "Installed node using NVM"
#   script:
#     - npm install
#     - CI='' npm run build
#   after_script:
#     - echo "Installation and build successful"
#   cache:
#     key: install-cache
#     paths:
#       - node_modules/

python_build:
  stage: py_build
  tags:
    - iprofiler
  before_script:
    - echo "Installing Python Dependencies"
    - apt-get install python3-venv
    - python3 -m venv venv
    - source ./venv/bin/activate
  script:
    - pip install wheel
    - pip install -r requirements.txt
    - cd flask-server && python3 app.py
  after_script:
    - echo "Installation and build successful Python Build"
    - deactivate
  # artifacts:
  #   paths:
  #     - build/*
